# Generated by Django 5.1.6 on 2025-02-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_prenda_tela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='description',
        ),
    ]
