# Generated by Django 5.1.6 on 2025-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_remove_tela_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
