# Generated by Django 5.1.6 on 2025-02-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_stock'),
    ]

    operations = [
    ]
