# Generated by Django 5.1.6 on 2025-02-28 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_auto_20250219_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'tallas',
            },
        ),
        migrations.AlterField(
            model_name='tela',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.stock'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_cellphone', models.CharField(max_length=15)),
                ('client_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=10)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.prenda')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.tela')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
