# Generated by Django 5.1.6 on 2025-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_talla_alter_tela_stock_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('cellphone', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
