# Generated by Django 5.1.6 on 2025-03-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_cellphone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_api.cliente'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
